In [1]:
import pandas as pd

In [2]:
data = [
    ["No", "Negative", "No", "19-35"],
    ["No", "Negative", "No", "36-55"],
    ["No", "Negative", "No", "56+"],
    ["No", "Negative", "No", "36-55"],
    ["No", "Negative", "No", "36-55"],
    ["No", "Negative", "No", "36-55"],
    ["No", "Negative", "No", "36-55"],
    ["No", "Negative", "Yes", "56+"],
    ["No", "Negative", "No", "19-35"],
    ["No", "Negative", "No", "19-35"],
    ["Yes", "Positive", "Yes", "19-35"],
    ["Yes", "Positive", "Yes", "56+"],
    ["No", "Negative", "No", "0-18"],
    ["No", "Negative", "Yes", "36-55"],
    ["No", "Negative", "No", "36-55"],
    ["Yes", "Positive", "Yes", "36-55"],
    ["No", "Negative", "No", "19-35"],
    ["No", "Negative", "No", "0-18"],
    ["No", "Negative", "No", "19-35"],
    ["No", "Negative", "No", "0-18"],
    ["Yes", "Positive", "Yes", "19-35"],
    ["Yes", "Positive", "Yes", "36-55"],
    ["No", "Negative", "Yes", "56+"],
    ["No", "Negative", "No", "19-35"],
    ["No", "Negative", "No", "36-55"],
]

In [3]:
df_25 = pd.DataFrame(data, columns=["Disease", "Test", "Symptom", "AgeGroup"])
df_25

   Disease      Test Symptom AgeGroup
0       No  Negative      No    19-35
1       No  Negative      No    36-55
2       No  Negative      No      56+
3       No  Negative      No    36-55
4       No  Negative      No    36-55
5       No  Negative      No    36-55
6       No  Negative      No    36-55
7       No  Negative     Yes      56+
8       No  Negative      No    19-35
9       No  Negative      No    19-35
10     Yes  Positive     Yes    19-35
11     Yes  Positive     Yes      56+
12      No  Negative      No     0-18
13      No  Negative     Yes    36-55
14      No  Negative      No    36-55
15     Yes  Positive     Yes    36-55
16      No  Negative      No    19-35
17      No  Negative      No     0-18
18      No  Negative      No    19-35
19      No  Negative      No     0-18
20     Yes  Positive     Yes    19-35
21     Yes  Positive     Yes    36-55
22      No  Negative     Yes      56+
23      No  Negative      No    19-35
24      No  Negative      No    36-55

In [5]:
p_dis = len(df_25[df_25["Disease"] == "Yes"]) / len(df_25)
p_pos = len(df_25[df_25["Test"] == "Positive"]) / len(df_25)
p_pos_dis = len (df_25[(df_25["Test"] == "Positive") & (df_25["Disease"] == "Yes")]) / len(df_25)

In [6]:
p_dis_pos = (p_pos_dis * p_dis) / p_pos
print("p(Disease/Positive) == ",p_dis_pos)

p(Disease/Positive) ==  0.20000000000000004